version: '3.8'

services:
  redis:
    container_name: ObiletRedis
    image: redis/redis-stack:latest
    # restart: always
    ports:
      - 6381:6379
    environment:
      - REDIS_PASSWORD=pass_obilet
      - REDIS_DATABASE=db_obilet
    volumes:
      - /Users/talhabuyukkose/Desktop/Projects/Interviews/Obilet/DockerVolume:/data/