version: '3.8'

services:
  redis:
    container_name: ObiletRedis
    image: redis/redis-stack:latest
    # restart: always
    ports:
      - 6381:6379
    environment:
      - REDIS_PASSWORD=pass_obilet
      - REDIS_DATABASE=db_obilet
    #volumes:
      #- /Users/talhabuyukkose/Desktop/Projects/Interviews/Obilet/DockerVolume:/data/

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"     # OTLP port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=localhost
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_PROTOCOL=udp/thrift.compact
    