version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      # - "6831:6831/udp"
      - "4317:4317"     # OTLP port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=localhost
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_JAEGER_PROTOCOL=udp/thrift.compact
   
    networks:
      - jaeger-example
networks:
  jaeger-example: